module JavaScript.AceAjax.Raw.Selection where
import qualified GHCJS.Types as GHCJS
import qualified GHCJS.Marshal as GHCJS
import qualified Data.Typeable
import GHCJS.FFI.TypeScript
import GHCJS.DOM.Types (HTMLElement)
import JavaScript.AceAjax.Raw.Types

foreign import javascript "$1.addEventListener($2,$3)" addEventListener :: (Selection) -> (GHCJS.JSString) -> (Function) -> IO (())
foreign import javascript "$1.moveCursorWordLeft()" moveCursorWordLeft :: (Selection) -> IO (())
foreign import javascript "$1.moveCursorWordRight()" moveCursorWordRight :: (Selection) -> IO (())
foreign import javascript "$1.fromOrientedRange($2)" fromOrientedRange :: (Selection) -> (Range) -> IO (())
foreign import javascript "$1.setSelectionRange($2)" setSelectionRange :: (Selection) -> (GHCJS.JSRef obj0) -> IO (())
foreign import javascript "$1.getAllRanges()" getAllRanges :: (Selection) -> IO (GHCJS.JSArray (Range))
foreign import javascript "$1.on($2,$3)" on :: (Selection) -> (GHCJS.JSString) -> (GHCJS.JSFun ((GHCJS.JSRef obj0) -> IO (GHCJS.JSRef obj1))) -> IO (())
foreign import javascript "$1.addRange($2)" addRange :: (Selection) -> (Range) -> IO (())
foreign import javascript "$1.isEmpty()" isEmpty :: (Selection) -> IO (GHCJS.JSBool)
foreign import javascript "$1.isMultiLine()" isMultiLine :: (Selection) -> IO (GHCJS.JSBool)
foreign import javascript "$1.getCursor()" getCursor :: (Selection) -> IO (Position)
foreign import javascript "$1.setSelectionAnchor($2,$3)" setSelectionAnchor :: (Selection) -> (GHCJS.JSNumber) -> (GHCJS.JSNumber) -> IO (())
foreign import javascript "$1.getSelectionAnchor()" getSelectionAnchor :: (Selection) -> IO (GHCJS.JSRef obj0)
foreign import javascript "$1.getSelectionLead()" getSelectionLead :: (Selection) -> IO (GHCJS.JSRef obj0)
foreign import javascript "$1.shiftSelection($2)" shiftSelection :: (Selection) -> (GHCJS.JSNumber) -> IO (())
foreign import javascript "$1.isBackwards()" isBackwards :: (Selection) -> IO (GHCJS.JSBool)
foreign import javascript "$1.getRange()" getRange :: (Selection) -> IO (Range)
foreign import javascript "$1.clearSelection()" clearSelection :: (Selection) -> IO (())
foreign import javascript "$1.selectAll()" selectAll :: (Selection) -> IO (())
foreign import javascript "$1.setRange($2,$3)" setRange :: (Selection) -> (Range) -> (GHCJS.JSBool) -> IO (())
foreign import javascript "$1.selectTo($2,$3)" selectTo :: (Selection) -> (GHCJS.JSNumber) -> (GHCJS.JSNumber) -> IO (())
foreign import javascript "$1.selectToPosition($2)" selectToPosition :: (Selection) -> (GHCJS.JSRef obj0) -> IO (())
foreign import javascript "$1.selectUp()" selectUp :: (Selection) -> IO (())
foreign import javascript "$1.selectDown()" selectDown :: (Selection) -> IO (())
foreign import javascript "$1.selectRight()" selectRight :: (Selection) -> IO (())
foreign import javascript "$1.selectLeft()" selectLeft :: (Selection) -> IO (())
foreign import javascript "$1.selectLineStart()" selectLineStart :: (Selection) -> IO (())
foreign import javascript "$1.selectLineEnd()" selectLineEnd :: (Selection) -> IO (())
foreign import javascript "$1.selectFileEnd()" selectFileEnd :: (Selection) -> IO (())
foreign import javascript "$1.selectFileStart()" selectFileStart :: (Selection) -> IO (())
foreign import javascript "$1.selectWordRight()" selectWordRight :: (Selection) -> IO (())
foreign import javascript "$1.selectWordLeft()" selectWordLeft :: (Selection) -> IO (())
foreign import javascript "$1.getWordRange()" getWordRange :: (Selection) -> IO (())
foreign import javascript "$1.selectWord()" selectWord :: (Selection) -> IO (())
foreign import javascript "$1.selectAWord()" selectAWord :: (Selection) -> IO (())
foreign import javascript "$1.selectLine()" selectLine :: (Selection) -> IO (())
foreign import javascript "$1.moveCursorUp()" moveCursorUp :: (Selection) -> IO (())
foreign import javascript "$1.moveCursorDown()" moveCursorDown :: (Selection) -> IO (())
foreign import javascript "$1.moveCursorLeft()" moveCursorLeft :: (Selection) -> IO (())
foreign import javascript "$1.moveCursorRight()" moveCursorRight :: (Selection) -> IO (())
foreign import javascript "$1.moveCursorLineStart()" moveCursorLineStart :: (Selection) -> IO (())
foreign import javascript "$1.moveCursorLineEnd()" moveCursorLineEnd :: (Selection) -> IO (())
foreign import javascript "$1.moveCursorFileEnd()" moveCursorFileEnd :: (Selection) -> IO (())
foreign import javascript "$1.moveCursorFileStart()" moveCursorFileStart :: (Selection) -> IO (())
foreign import javascript "$1.moveCursorLongWordRight()" moveCursorLongWordRight :: (Selection) -> IO (())
foreign import javascript "$1.moveCursorLongWordLeft()" moveCursorLongWordLeft :: (Selection) -> IO (())
foreign import javascript "$1.moveCursorBy($2,$3)" moveCursorBy :: (Selection) -> (GHCJS.JSNumber) -> (GHCJS.JSNumber) -> IO (())
foreign import javascript "$1.moveCursorToPosition($2)" moveCursorToPosition :: (Selection) -> (GHCJS.JSRef obj0) -> IO (())
foreign import javascript "$1.moveCursorTo($2,$3,$4)" moveCursorTo :: (Selection) -> (GHCJS.JSNumber) -> (GHCJS.JSNumber) -> (GHCJS.JSBool) -> IO (())
foreign import javascript "$1.moveCursorToScreen($2,$3,$4)" moveCursorToScreen :: (Selection) -> (GHCJS.JSNumber) -> (GHCJS.JSNumber) -> (GHCJS.JSBool) -> IO (())
