module JavaScript.AceAjax.Raw.Types where
import qualified GHCJS.Types as GHCJS
import qualified GHCJS.Marshal as GHCJS
import qualified Data.Typeable
import GHCJS.FFI.TypeScript
import GHCJS.DOM.Types (HTMLElement)
newtype Delta = Delta (GHCJS.JSRef Delta)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype EditorCommand = EditorCommand (GHCJS.JSRef EditorCommand)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype CommandManager = CommandManager (GHCJS.JSRef CommandManager)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype Annotation = Annotation (GHCJS.JSRef Annotation)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype TokenInfo = TokenInfo (GHCJS.JSRef TokenInfo)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype Position = Position (GHCJS.JSRef Position)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype KeyBinding = KeyBinding (GHCJS.JSRef KeyBinding)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype TextMode = TextMode (GHCJS.JSRef TextMode)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype Ace = Ace (GHCJS.JSRef Ace)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype Anchor = Anchor (GHCJS.JSRef Anchor)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype BackgroundTokenizer = BackgroundTokenizer (GHCJS.JSRef BackgroundTokenizer)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype Document = Document (GHCJS.JSRef Document)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype IEditSession = IEditSession (GHCJS.JSRef IEditSession)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype Editor = Editor (GHCJS.JSRef Editor)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype PlaceHolder = PlaceHolder (GHCJS.JSRef PlaceHolder)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype IRangeList = IRangeList (GHCJS.JSRef IRangeList)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype Range = Range (GHCJS.JSRef Range)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype RenderLoop = RenderLoop (GHCJS.JSRef RenderLoop)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype ScrollBar = ScrollBar (GHCJS.JSRef ScrollBar)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype Search = Search (GHCJS.JSRef Search)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype Selection = Selection (GHCJS.JSRef Selection)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype Split = Split (GHCJS.JSRef Split)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype TokenIterator = TokenIterator (GHCJS.JSRef TokenIterator)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype Tokenizer = Tokenizer (GHCJS.JSRef Tokenizer)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype UndoManager = UndoManager (GHCJS.JSRef UndoManager)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
newtype VirtualRenderer = VirtualRenderer (GHCJS.JSRef VirtualRenderer)
  deriving (Data.Typeable.Typeable, GHCJS.ToJSRef, GHCJS.FromJSRef)
